FROM ghcr.io/argotorg/sourcify/server:latest

COPY --chown=node:node sourcify-chains.json /home/app/services/server/dist/sourcify-chains.json
COPY --chown=node:node config.js /home/app/services/server/dist/config/local.js